# Build codegraph via docker.
# See also Dockerfile at the root of the project.
# coupling: very similar to the docker.yml in codemap

name: docker

on:
  pull_request_target: {}
  workflow_dispatch: null
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ocaml:
          - 4.14.2
          - 5.2.1
    steps:
      - uses: actions/checkout@v4
      # optional if don't need multi-arch build
      - uses: docker/setup-buildx-action@v3
      - run: docker build -t "codegraph" --build-arg OCAML_VERSION=${{matrix.ocaml}} .
